# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Proxem Engineering Blog
email: jmm@proxem.com
description: > # this means to ignore newlines until "baseurl:"
  News, tutorials, applications and everything related to Research at Proxem.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://proxem.github.io" # the base hostname & protocol for your site
twitter_username: proxem
github_username:  proxem

# Build settings
markdown: redcarpet

highlighter: pygments
